resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      productos:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 2s
    instances:
      productos:
        base-config: defecto
spring:
  cloud:
    gateway:
      routes:
        - id: msvc-productos
          uri: lb://msvc-productos
          predicates:
            - Path=/api/productos/**
          #  - Header=token,1234
          #  - Method=GET,POST
          #  - Query=color
           # - Cookie=color,azul
          filters:
            - name: CircuitBreaker
              args:
                name: productos
                statusCodes: 500,404
                fallbackUri: forward:/api/items/9/cantidad/5
            - StripPrefix=2
        # una manera de aplicar filtros
        #    - name: Ejemplo
        #      args:
        #        mensaje: hola mi mensaje personalizado
        #        cookieNombre: usuario
        #        cookieValor: DamianAdamo
            - EjemploCookie= Hola mi mensaje personalizado, usuario, Francesca
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
              - StripPrefix=2
              - AddRequestHeader=token-request,123456
              - AddResponseHeader=token-response,12345678
              - AddRequestParameter=nombre,damian
        - id: msvc-usuarios
          uri: lb://msvc-usuarios
          predicates:
            - Path=/api/usuarios/**
          filters:
            - StripPrefix=2
        - id: msvc-oauth
          uri: lb://msvc-oauth
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=2